import { CSSProperties } from 'react';
type Styles = {
  [key: string]: CSSProperties;
};

// --- 스타일 정의 ---
export const styles: Styles = {
  container: {
    padding: '24px',
    fontFamily: 'sans-serif',
    color: 'white',
    height: '100%',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#111827',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '30px',
  },
  title: {
    fontSize: '20px',
    fontWeight: 'bold',
    margin: 0,
  },
  backButton: {
    background: 'none',
    border: 'none',
    color: '#d1d5db',
    fontSize: '16px',
    cursor: 'pointer',
    padding: '4px 8px',
    borderRadius: '4px',
  },
  content: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '30px',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  sectionTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#9ca3af',
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    marginBottom: '8px',
  },
  profileCard: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: '#1f2937',
    padding: '16px',
    borderRadius: '12px',
    gap: '16px',
  },
  avatar: {
    width: '48px',
    height: '48px',
    borderRadius: '50%',
    backgroundColor: '#3b82f6',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '20px',
    fontWeight: 'bold',
    color: 'white',
  },
  userInfo: {
    display: 'flex',
    flexDirection: 'column',
  },
  email: {
    fontSize: '16px',
    fontWeight: '500',
    color: 'white',
  },
  status: {
    fontSize: '13px',
    color: '#4ade80',
    display: 'flex',
    alignItems: 'center',
    marginTop: '4px',
  },
  statusDot: {
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    backgroundColor: '#4ade80',
    marginRight: '6px',
  },
  settingItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#1f2937',
    padding: '16px',
    borderRadius: '12px',
  },
  settingLabel: {
    fontSize: '15px',
    fontWeight: '500',
    color: 'white',
    marginBottom: '4px',
  },
  settingDesc: {
    fontSize: '12px',
    color: '#9ca3af',
  },
  toggleButton: {
    width: '48px',
    height: '24px',
    borderRadius: '999px',
    padding: '2px',
    border: 'none',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    transition: 'background-color 0.2s',
  },
  toggleHandle: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    backgroundColor: 'white',
    boxShadow: '0 1px 2px rgba(0, 0, 0, 0.2)',
  },
  footerSection: {
    marginTop: 'auto',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
  },
  versionInfo: {
    fontSize: '12px',
    color: '#4b5563',
  },
  logoutButton: {
    width: '100%',
    padding: '14px',
    backgroundColor: '#ef4444',
    color: 'white',
    border: 'none',
    borderRadius: '12px',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
};